# Generated by Django 5.2.5 on 2025-09-24 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companylink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='companylink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_links_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='companies', through='companyApp.CompanyMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='companycontact',
            index=models.Index(fields=['company', 'is_primary'], name='companyApp__company_b4aac5_idx'),
        ),
        migrations.AddIndex(
            model_name='companycontact',
            index=models.Index(fields=['company', 'email'], name='companyApp__company_7c7ef1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companycontact',
            unique_together={('company', 'email')},
        ),
        migrations.AddIndex(
            model_name='companylink',
            index=models.Index(fields=['company', 'visibility', 'is_active', 'sort_order'], name='companyApp__company_5cb2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='companylink',
            index=models.Index(fields=['company', 'section'], name='companyApp__company_58993b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companylink',
            unique_together={('company', 'label', 'section')},
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['company', 'user', 'is_active'], name='companyApp__company_0bb797_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['company', 'role'], name='companyApp__company_c30e08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companymembership',
            unique_together={('company', 'user')},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companyApp__name_a038b8_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='companyApp__slug_52ac3a_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='companyApp__status_cbffb7_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['pipeline_status'], name='companyApp__pipelin_03b7db_idx'),
        ),
    ]
