# Generated by Django 5.2.5 on 2025-09-24 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DncReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'label'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='companyApp__is_acti_58de6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DncEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=10)),
                ('value_raw', models.CharField(help_text='Original value as entered', max_length=254)),
                ('value_normalized', models.CharField(editable=False, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, help_text='e.g., user_request, bounce, manual', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dnc_entries', to='companyApp.companycontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dnc_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dnc_entries', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='companyApp.dncreason')),
            ],
            options={
                'ordering': ('-is_active', 'channel', 'value_normalized'),
                'indexes': [models.Index(fields=['channel', 'value_normalized', 'is_active'], name='companyApp__channel_04338b_idx'), models.Index(fields=['user', 'is_active'], name='companyApp__user_id_e2a0b2_idx'), models.Index(fields=['contact', 'is_active'], name='companyApp__contact_363c9c_idx')],
                'unique_together': {('channel', 'value_normalized', 'is_active')},
            },
        ),
    ]
