# Generated by Django 5.2.5 on 2025-09-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable id for dismissing in localStorage.', max_length=80, unique=True)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('message_html', models.TextField(help_text='Supports HTML')),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('EMPLOYEE', 'Employees'), ('CLIENT', 'Clients'), ('PUBLIC', 'Public / Logged-out')], default='ALL', max_length=12)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('DANGER', 'Danger')], default='INFO', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('dismissible', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Lower shows first')),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('priority', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable id for dismissing in localStorage.', max_length=80, unique=True)),
                ('version_num', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('date_of_release', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('date_of_release', '-updated_at'),
            },
        ),
    ]
