# Generated by Django 5.2.5 on 2025-09-18 15:39

import companyApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=120)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state_region', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='USA', max_length=120)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='PNG/JPEG/WebP, up to 3MB.', null=True, upload_to=companyApp.models.logo_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), companyApp.models.validate_logo_size])),
                ('logo_external_url', models.URLField(blank=True, help_text='Optional external logo URL (e.g., Google Drive shared link).')),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='PROSPECT', max_length=20)),
                ('pipeline_status', models.CharField(blank=True, choices=[('NEW', 'New'), ('HOLDING', 'Holding'), ('IN_PROGRESS', 'In Progress'), ('ONGOING', 'On Going'), ('FINISHED', 'Finished'), ('INACTIVE', 'Inactive')], default='', max_length=20)),
                ('consultation_sheet_url', models.URLField(blank=True)),
                ('first_contact_at', models.DateField(blank=True, null=True)),
                ('last_contact_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-is_primary', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('section', models.CharField(blank=True, choices=[('GENERAL', 'General'), ('HOSTING', 'Hosting / CMS'), ('DOMAINS', 'Domains / DNS'), ('ANALYTICS', 'Analytics'), ('DESIGN', 'Design (Figma, etc.)'), ('REPOSITORY', 'Repositories'), ('ENVIRON', 'Environments'), ('DOCS', 'Docs / Drive'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (optional)', max_length=200)),
                ('visibility', models.CharField(choices=[('EMPLOYEE', 'Employee only'), ('SHARED', 'Client & Employee')], default='EMPLOYEE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('key_name', models.CharField(blank=True, help_text='Name of key/credential (do not store secrets)', max_length=120)),
                ('key_hint', models.CharField(blank=True, help_text='Where the key lives (e.g., vault ref)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'label'),
            },
        ),
    ]
