# Generated by Django 5.2.5 on 2025-09-15 15:07

import companyApp.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-is_primary', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('section', models.CharField(blank=True, choices=[('GENERAL', 'General'), ('HOSTING', 'Hosting / CMS'), ('DOMAINS', 'Domains / DNS'), ('ANALYTICS', 'Analytics'), ('DESIGN', 'Design (Figma, etc.)'), ('REPOSITORY', 'Repositories'), ('ENVIRON', 'Environments'), ('DOCS', 'Docs / Drive'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (optional)', max_length=200)),
                ('visibility', models.CharField(choices=[('EMPLOYEE', 'Employee only'), ('SHARED', 'Client & Employee')], default='EMPLOYEE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('key_name', models.CharField(blank=True, help_text='Name of key/credential (do not store secrets)', max_length=120)),
                ('key_hint', models.CharField(blank=True, help_text='Where the key lives (e.g., vault ref)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='consultation_sheet_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='first_contact_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_contact_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG/JPEG/WebP, up to 3MB.', null=True, upload_to=companyApp.models.logo_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), companyApp.models.validate_logo_size]),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_external_url',
            field=models.URLField(blank=True, help_text='Optional external logo URL (e.g., Google Drive shared link).'),
        ),
        migrations.AddField(
            model_name='company',
            name='pipeline_status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('HOLDING', 'Holding'), ('IN_PROGRESS', 'In Progress'), ('ONGOING', 'On Going'), ('FINISHED', 'Finished'), ('INACTIVE', 'Inactive')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='companyApp__status_cbffb7_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['pipeline_status'], name='companyApp__pipelin_03b7db_idx'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companylink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='companylink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_links_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='companycontact',
            index=models.Index(fields=['company', 'is_primary'], name='companyApp__company_b4aac5_idx'),
        ),
        migrations.AddIndex(
            model_name='companycontact',
            index=models.Index(fields=['company', 'email'], name='companyApp__company_7c7ef1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companycontact',
            unique_together={('company', 'email')},
        ),
        migrations.AddIndex(
            model_name='companylink',
            index=models.Index(fields=['company', 'visibility', 'is_active', 'sort_order'], name='companyApp__company_5cb2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='companylink',
            index=models.Index(fields=['company', 'section'], name='companyApp__company_58993b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companylink',
            unique_together={('company', 'label', 'section')},
        ),
    ]
