# Generated by Django 5.2.5 on 2025-09-24 15:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('base_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CostTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('min_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_total', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank for 'no upper limit'.", max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'min_total', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed amount')], default='PERCENT', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='JobRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ProposalAppliedDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProposalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_type', models.CharField(choices=[('NONE', 'None'), ('PERCENT', 'Percent'), ('FIXED', 'Fixed')], default='NONE', max_length=10)),
                ('deposit_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remaining_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estimate_low', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estimate_high', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estimate_manual', models.BooleanField(default=False, help_text="If checked, keep the selected tier and don't auto-update from totals.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProposalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('SIGNED', 'Signed'), ('UPDATED', 'Updated'), ('COMMENT', 'Comment')], max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProposalLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProposalRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-is_primary', 'email'),
            },
        ),
        migrations.CreateModel(
            name='ProposalViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('default_hours', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('default_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('base_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='proposalApp.basesetting')),
                ('job_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='proposalApp.jobrate')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('base_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_items', to='proposalApp.basesetting')),
                ('catalog_item', models.ForeignKey(help_text='Choose from the predefined items list.', on_delete=django.db.models.deletion.PROTECT, related_name='draft_items', to='proposalApp.catalogitem')),
                ('job_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_items', to='proposalApp.jobrate')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('amount_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_type', models.CharField(choices=[('NONE', 'None'), ('PERCENT', 'Percent'), ('FIXED', 'Fixed')], default='NONE', max_length=10)),
                ('deposit_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remaining_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sign_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_proposals', to='companyApp.company')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
