# Generated by Django 5.2.5 on 2025-09-24 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyApp', '0002_initial'),
        ('proposalApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalapplieddiscount',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_discounts', to='proposalApp.proposal'),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_drafts', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposalApp.discount'),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='estimate_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='proposalApp.costtier'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='converted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='proposalApp.proposaldraft'),
        ),
        migrations.AddField(
            model_name='draftitem',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proposalApp.proposaldraft'),
        ),
        migrations.AddField(
            model_name='proposalevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalevent',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proposalApp.proposal'),
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='base_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_items', to='proposalApp.basesetting'),
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='job_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_items', to='proposalApp.jobrate'),
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='proposalApp.proposal'),
        ),
        migrations.AddField(
            model_name='proposalrecipient',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='proposalApp.proposal'),
        ),
        migrations.AddField(
            model_name='proposalviewer',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_viewers', to='proposalApp.proposal'),
        ),
        migrations.AddField(
            model_name='proposalviewer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='proposals_shared_with', through='proposalApp.ProposalViewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='proposalrecipient',
            unique_together={('proposal', 'email')},
        ),
        migrations.AddIndex(
            model_name='proposalviewer',
            index=models.Index(fields=['proposal', 'user'], name='proposalApp_proposa_1784a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proposalviewer',
            unique_together={('proposal', 'user')},
        ),
    ]
