# Generated by Django 5.2.5 on 2025-09-24 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0003_proposaldraft_approval_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approver_user',
            field=models.ForeignKey(blank=True, help_text='Employee who approved the draft and should countersign after client signs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_to_countersign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='countersign_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='countersign_required',
            field=models.BooleanField(default=True, help_text='If true, an internal countersign is required after the client signs.'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='countersigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='countersigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_countersigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
