# Generated by Django 5.2.5 on 2025-09-24 18:51

import django.core.validators
import proposalApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0004_proposal_approver_user_proposal_countersign_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='pdf',
            field=models.FileField(blank=True, help_text='Upload a finalized PDF; optional if you generate on the fly.', null=True, upload_to=proposalApp.models.proposal_pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf']), proposalApp.models.validate_proposal_pdf_size]),
        ),
    ]
