# Generated by Django 5.2.5 on 2025-09-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('date_of_release', '-updated_at')},
        ),
        migrations.RenameField(
            model_name='version',
            old_name='dateOfRelease',
            new_name='date_of_release',
        ),
        migrations.AddField(
            model_name='version',
            name='slug',
            field=models.SlugField(default=1, help_text='Stable id for dismissing in localStorage.', max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
