# Generated by Django 5.2.5 on 2025-09-24 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_can_view_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='client_can_view_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_can_view_status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProjectViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_view_grants', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='projectApp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_visible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'user'], name='projectApp__project_3a328b_idx')],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
