# Generated by Django 5.2.5 on 2025-09-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CLIENT', 'Client'), ('ADMIN', 'Admin'), ('OWNER', 'Owner')], default='CLIENT', max_length=20),
        ),
    ]
