# Generated by Django 5.2.5 on 2025-09-12 14:52

import django.core.validators
import userApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='JPEG/PNG/WebP, up to 3MB.', null=True, upload_to=userApp.models.avatar_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), userApp.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='JPEG/PNG/WebP, up to 3MB.', null=True, upload_to=userApp.models.avatar_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), userApp.models.validate_image_size]),
        ),
    ]
