# Generated by Django 5.2.5 on 2025-09-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0001_initial'),
        ('userApp', '0007_company_clientprofile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profiles', to='companyApp.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
