# Generated by Django 5.2.5 on 2025-09-15 18:13

import django.core.validators
import django.db.models.deletion
import projectApp.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PREVIEW', 'Preview'), ('STAGING', 'Staging'), ('PROD', 'Production')], default='PREVIEW', max_length=10)),
                ('url', models.URLField(blank=True)),
                ('health', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('UP', 'Up'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('MAINTENANCE', 'Maintenance')], default='UNKNOWN', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('project', 'kind'),
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('section', models.CharField(blank=True, choices=[('GENERAL', 'General'), ('ENVIRON', 'Environments'), ('REPOSITORY', 'Repositories'), ('DESIGN', 'Design (Figma, etc.)'), ('DOCS', 'Docs / Drive'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('visibility', models.CharField(choices=[('EMPLOYEE', 'Employee only'), ('SHARED', 'Client & Employee')], default='EMPLOYEE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('sort_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Project Manager'), ('DESIGN', 'Design'), ('DEV', 'Developer'), ('QA', 'QA'), ('PM', 'Producer/PM'), ('CLIENT', 'Client'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('project', 'role', 'user__username'),
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PLANNED', 'Planned'), ('STARTED', 'Started'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='PLANNED', max_length=12)),
                ('is_client_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'due_date', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Internal (staff only)'), ('SHARED', 'Shared with client')], default='SHARED', max_length=10)),
                ('percent_complete_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('pinned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-pinned', '-posted_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projectApp.models.update_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp', 'docx', 'xlsx', 'txt']), projectApp.models.validate_file_size])),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Human-friendly project code', max_length=240, unique=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETE', 'Complete'), ('ARCHIVED', 'Archived')], default='PLANNING', max_length=20)),
                ('stage', models.CharField(blank=True, choices=[('DISCOVERY', 'Discovery'), ('DESIGN', 'Design'), ('BUILD', 'Build'), ('QA', 'QA / UAT'), ('LAUNCH', 'Launch'), ('POST', 'Post-Launch')], default='', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('scope_summary', models.TextField(blank=True)),
                ('percent_complete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_launch_date', models.DateField(blank=True, null=True)),
                ('actual_launch_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companyApp.company')),
            ],
            options={
                'ordering': ('company__name', 'name'),
            },
        ),
    ]
