# Generated by Django 5.2.5 on 2025-09-25 22:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_project_client_can_view_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.PositiveSmallIntegerField(default=3, help_text='Project urgency (1=highest, 9=lowest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='project',
            name='show_priority_to_client',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='Task priority (1=highest, 9=lowest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='TODO', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('planned_week_start', models.DateField(blank=True, help_text='Week start (e.g. Monday) this task is planned for.', null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('percent_complete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_client_visible', models.BooleanField(default=True, help_text='If false, clients cannot see this task at all.')),
                ('show_priority_to_client', models.BooleanField(default=False, help_text="If true AND task is visible, clients can see the task's priority number.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignees', models.ManyToManyField(blank=True, help_text='Team members responsible for this task.', related_name='assigned_project_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projectApp.project')),
            ],
            options={
                'ordering': ('project', 'planned_week_start', 'priority', 'sort_order', 'due_date', 'pk'),
                'indexes': [models.Index(fields=['project', 'status'], name='projectApp__project_734d98_idx'), models.Index(fields=['project', 'planned_week_start'], name='projectApp__project_6bd8f0_idx'), models.Index(fields=['project', 'priority'], name='projectApp__project_47414c_idx'), models.Index(fields=['project', 'is_client_visible'], name='projectApp__project_8d7e33_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectWeekNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Normalized to week start (e.g., Monday).')),
                ('body', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Internal (staff only)'), ('SHARED', 'Shared with client')], default='SHARED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_week_notes_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_notes', to='projectApp.project')),
            ],
            options={
                'ordering': ('-week_start', 'pk'),
                'indexes': [models.Index(fields=['project', '-week_start'], name='projectApp__project_77c634_idx')],
                'unique_together': {('project', 'week_start')},
            },
        ),
    ]
