# Generated by Django 5.2.5 on 2025-09-18 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address1', models.CharField(blank=True, max_length=160)),
                ('address2', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='USA', max_length=60)),
                ('website_url', models.CharField(blank=True, help_text='Leave blank if no site', max_length=300, validators=[django.core.validators.URLValidator()])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('RES', 'Researched'), ('RDY', 'Ready to Contact'), ('EML', 'Emailed'), ('RPL', 'Replied'), ('BNC', 'Bounced'), ('UNS', 'Unsubscribed'), ('WON', 'Converted'), ('LST', 'Not a Fit')], default='NEW', max_length=3)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=200)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('unsubscribe_token', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
