# Generated by Django 5.2.5 on 2025-09-15 18:13

import django.core.validators
import django.db.models.deletion
import proposalApp.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed amount')], default='PERCENT', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='PricingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ProposalAppliedDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProposalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('questionnaire', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('CONVERTED', 'Converted to Proposal'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=12)),
                ('internal_notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_type', models.CharField(choices=[('NONE', 'None'), ('PERCENT', 'Percent of total'), ('FIXED', 'Fixed amount')], default='NONE', max_length=10)),
                ('deposit_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProposalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('SIGNED', 'Signed'), ('DOWNLOADED', 'Downloaded'), ('COMMENT', 'Comment'), ('UPDATED', 'Updated'), ('DECLINED', 'Declined')], max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProposalLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProposalRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-is_primary', 'email'),
            },
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-effective_from', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('FIXED', 'Fixed Fee'), ('RECURRING', 'Recurring')], default='HOURLY', max_length=12)),
                ('default_hours', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('fixed_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('period', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('OTHER', 'Other')], default='', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DraftDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_usages', to='proposalApp.discount')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LaborRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='proposalApp.pricingrole')),
            ],
            options={
                'ordering': ('sort_order', 'role__code'),
            },
        ),
        migrations.CreateModel(
            name='DraftSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('FIXED', 'Fixed Fee'), ('RECURRING', 'Recurring')], max_length=12)),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('extended_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes_internal', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposalApp.pricingrole')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('SIGNED', 'Signed'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('amount_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('deposit_type', models.CharField(choices=[('NONE', 'None'), ('PERCENT', 'Percent of total'), ('FIXED', 'Fixed amount')], default='NONE', max_length=10)),
                ('deposit_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sign_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_unsigned', models.FileField(blank=True, help_text='Employee-only; retained for history.', null=True, upload_to=proposalApp.models.unsigned_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('pdf_signed', models.FileField(blank=True, help_text='Client-visible after signing.', null=True, upload_to=proposalApp.models.signed_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('signed_by_name', models.CharField(blank=True, max_length=200)),
                ('signed_by_email', models.EmailField(blank=True, max_length=254)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signature_text', models.CharField(blank=True, max_length=200)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=proposalApp.models.signature_image_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('signature_payload', models.JSONField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='companyApp.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_for_contact', to='companyApp.companycontact')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
