# Generated by Django 5.2.5 on 2025-09-15 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyApp', '0002_initial'),
        ('proposalApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalapplieddiscount',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_discounts', to='proposalApp.proposal'),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_drafts', to='companyApp.company'),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draftselection',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='proposalApp.proposaldraft'),
        ),
        migrations.AddField(
            model_name='draftdiscount',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='proposalApp.proposaldraft'),
        ),
        migrations.AddField(
            model_name='proposalevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalevent',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proposalApp.proposal'),
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='proposalApp.proposal'),
        ),
        migrations.AddField(
            model_name='proposalrecipient',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='proposalApp.proposal'),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='proposalApp.ratecard'),
        ),
        migrations.AddField(
            model_name='laborrate',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='proposalApp.ratecard'),
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposalApp.pricingrole'),
        ),
        migrations.AddField(
            model_name='draftselection',
            name='catalog_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_selections', to='proposalApp.servicecatalogitem'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['company', 'status'], name='proposalApp_company_a2ae43_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['sign_token'], name='proposalApp_sign_to_14ee28_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['title'], name='proposalApp_title_4f16cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('company', 'title', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='draftdiscount',
            unique_together={('draft', 'discount')},
        ),
        migrations.AlterUniqueTogether(
            name='proposalrecipient',
            unique_together={('proposal', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='laborrate',
            unique_together={('rate_card', 'role')},
        ),
    ]
