# Generated by Django 5.2.5 on 2025-09-18 16:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftitem',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('default_hours', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('default_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('base_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='proposalApp.basesetting')),
                ('job_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='proposalApp.jobrate')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='draftitem',
            name='catalog_item',
            field=models.ForeignKey(default=1, help_text='Choose from the predefined items list.', on_delete=django.db.models.deletion.PROTECT, related_name='draft_items', to='proposalApp.catalogitem'),
            preserve_default=False,
        ),
    ]
