# Generated by Django 5.2.5 on 2025-09-18 16:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0003_alter_draftitem_name_catalogitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('min_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_total', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank for 'no upper limit'.", max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'min_total', 'code'),
            },
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='estimate_high',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='estimate_low',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='estimate_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='proposalApp.costtier'),
        ),
    ]
