# Generated by Django 5.2.5 on 2025-09-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0004_costtier_proposaldraft_estimate_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldraft',
            name='estimate_manual',
            field=models.BooleanField(default=False, help_text="If checked, keep the selected tier and don't auto-update from totals."),
        ),
    ]
