# Generated by Django 5.2.5 on 2025-09-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0005_proposal_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaldraft',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted')], db_index=True, default='DRAFT', max_length=12),
        ),
    ]
