# Generated by Django 5.2.5 on 2025-09-29 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0006_alter_proposaldraft_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldraft',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, help_text='Admin/Owner assigned to review this draft.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_drafts_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
