# Generated by Django 5.2.5 on 2025-09-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalApp', '0007_proposaldraft_assigned_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='proposal',
            name='contact_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
